backend:
  name: git-gateway
  branch: main
local_backend: true
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: headerNav
        file: "_data/headerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Footer Menu"
        name: footerNav
        file: "_data/footerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Categories"
        name: categories
        file: "_data/categories.yml"
        fields:
          - label: "Categories"
            label_singular: "Category Item"
            name: categoryItems
            widget: list
            fields:
              - { label: "Category name", name: categoryName, widget: string }
              - { label: "Slug", name: categorySlug, widget: string }
      # - label: "Submenus"
      #   name: subMenu
      #   file: "_data/subMenu.yml"
      #   fields:
      #     - label: "Nav Items"
      #       label_singular: "Nav Item"
      #       name: navItems
      #       widget: list
      #       summary: "{{fields.navtitle}}"
      #       collapsed: true
      #       types:
      #         - label: "Navigation List"
      #           name: navList
      #           widget: list
      #           fields:
      #             - label: "Navigation Title"
      #               name: "navtitle"
      #               widget: string
      #             - {
      #                 label: "Parent page",
      #                 widget: relation,
      #                 name: parent_relation,
      #                 required: true,
      #                 multiple: false,
      #                 collection: pages,
      #                 valueField: "{{slug}}",
      #                 searchFields: ["title"],
      #                 displayFields: ["title"],
      #               }
      #             - label: "Navigation item"
      #               name: navItem
      #               widget: object
      #               fields:
      #                 - label: "Add a Link"
      #                   name: link
      #                   widget: list
      #                   summary: "{{fields.displayText}}"
      #                   collapsed: true
      #                   types:
      #                     - label: "Link"
      #                       name: linkObject
      #                       widget: object
      #                       fields:
      #                         - {
      #                             label: "Display Text",
      #                             name: displayText,
      #                             widget: string,
      #                             required: true,
      #                           }
      #                         - {
      #                             label: "page",
      #                             widget: relation,
      #                             name: url,
      #                             required: true,
      #                             multiple: false,
      #                             collection: pages,
      #                             valueField: "{{slug}}",
      #                             searchFields: ["title"],
      #                             displayFields: ["title"],
      #                           }

  - name: pages
    label: Pages
    title: Page
    label_singular: "Page"
    folder: src/content/pages
    create: true
    nested:
      depth: 6 # max depth to show in the collection tree
      summary: "{{meta.path}}"
    slug: "{{slug}}"
    identifier_field: name
    preview_path: "{{fields.permalink}}"
    # permalink: "{{ page.filePathStem }}.html"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/page.njk",
        }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "string",
          required: true,
          default: "{{ page.filePathStem }}.html",
          hint: "Must be relative path (e.g. main/sub/index.html). Don't forget the .html extension",
        }
      - {
          label: "Category",
          name: category,
          widget: relation,
          required: true,
          multiple: false,
          collection: categories,
          valueField: "{{title}}",
          searchFields: ["title", "slug"],
          displayFields: ["title"],
        }
      - {
          label: "Parent page",
          name: parent,
          widget: relation,
          required: false,
          multiple: false,
          collection: pages,
          valueField: "{{title}}",
          searchFields: ["title", "slug"],
          displayFields: ["title"],
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - {
                  label: "Content",
                  name: content,
                  widget: markdown,
                  buttons: ["bold", "italic", "link"],
                  required: false,
                }
          - label: "Rich Text Block"
            name: textBlock
            widget: object
            fields:
              - {
                  label: "Heading",
                  name: heading,
                  widget: string,
                  required: false,
                }
              - { label: "Content", name: content, widget: markdown }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - {
          label: "Meta description",
          name: "metaDescription",
          widget: "string",
          pattern: [".{12,}", "Must have at least 12 characters"],
        }
      - {
          label: "Meta keywords",
          name: "metaKeywords",
          widget: "string",
          pattern: [".{3,}", "Must have at least 12 characters"],
        }
    meta:
      {
        path:
          {
            widget: string,
            label: "Path",
            index_file: "index",
            hint: "Path can be a sub-folder (e.g. main/sub)",
          },
      }
