backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: headerNav
        file: "_data/headerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Footer Menu"
        name: footerNav
        file: "_data/footerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Submenus"
        name: subMenu
        file: "_data/subMenu.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: navItems
            widget: list
            types:
              - label: "Sub Navigation"
                name: subNav
                widget: object
                fields:
                  - label: "navtitle"
                    name: "navtitle"
                    widget: string
                  - label: "link"
                    name: link
                    widget: list
                    types:
                      - {
                          label: "Display Text",
                          name: displayText,
                          widget: string,
                        }
                      - { label: URL, name: url, widget: string }

  - name: pages
    label: Pages
    title: Page
    label_singular: "Page"
    folder: src/content/pages
    create: true
    nested:
      depth: 6 # max depth to show in the collection tree
      summary: "{{meta.path}}"
    slug: "{{slug}}"
    preview_path: "{{permalink}}"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/page.njk",
        }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "string",
          required: true,
          valueField: "{{slug}}/index.html",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - {
                  label: "Content",
                  name: content,
                  widget: markdown,
                  buttons: ["bold", "italic", "link"],
                  required: false,
                }
          - label: "Rich Text Block"
            name: textBlock
            widget: object
            fields:
              - {
                  label: "Heading",
                  name: heading,
                  widget: string,
                  required: false,
                }
              - { label: "Content", name: content, widget: markdown }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
          - {
              widget: relation,
              name: child_relation,
              label: "Child pages",
              required: false,
              multiple: true,
              collection: pages,
              valueField: "{{slug}}",
              searchFields: ["title"],
              displayFields: ["title"],
            }
          - {
              widget: relation,
              name: parent_relation,
              label: "Parent page",
              required: false,
              multiple: false,
              collection: pages,
              valueField: "{{slug}}",
              searchFields: ["title"],
              displayFields: ["title"],
            }
      - {
          label: "Meta description",
          name: "metaDescription",
          widget: "string",
          pattern: [".{12,}", "Must have at least 12 characters"],
        }
      - {
          label: "Meta keywords",
          name: "metaKeywords",
          widget: "string",
          pattern: [".{3,}", "Must have at least 12 characters"],
        }
    meta:
      {
        path:
          {
            widget: string,
            label: "Path",
            index_file: "index",
            hint: "Path can be a sub-folder (e.g. main/sub)",
          },
      }
